# Generated by Django 5.2.15 on 2026-07-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='document',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
