# Generated by Django 5.2.15 on 2026-07-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_updated_at_document_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
