# Generated by Django 5.2.15 on 2026-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(default='error_message', max_length=200),
            preserve_default=False,
        ),
    ]
