# Generated by Django 5.2.15 on 2026-07-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentchunk_embedding_alter_document_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
