# Generated by Django 5.2.15 on 2026-07-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_extracted_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='extracted_data',
            new_name='extracted_email',
        ),
        migrations.AddField(
            model_name='document',
            name='extracter_phone',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
