# Generated by Django 5.2.15 on 2026-07-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rename_extracted_data_document_extracted_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='extracted_email',
            new_name='extracted_emails',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='extracter_phone',
            new_name='extracted_phones',
        ),
    ]
